### ISSUE TITLE
Network lost 

### ISSUE THREAD

**Issue by Yuvrajroy10** [Al3XKOoL/android_device_wiko_rainbow-WIP#3]
The rom was great but problem with network, network lost when calling someone or messaging someone. Fix it pls

**Comment by Al3XKOoL** [comment]
Wath version you have installed?

**Comment by Yuvrajroy10** [comment]
Beta 4

**Comment by Al3XKOoL** [comment]
Can you share your ril-log after some network lost?

Also country and provider please.

**Comment by Yuvrajroy10** [comment]
It say, Restricted access changed: data service is blocked
Or  restricted access changed: Voice service is blocked 
Country -  India 
Provider - Both are Vodafone

**Comment by Yuvrajroy10** [comment]
OR means Sometime

**Comment by Al3XKOoL** [comment]
Please try set network mode to 2G or 3G only. 

Get same problem?

**Comment by Yuvrajroy10** [comment]
Yes I have tried that but not working. Pls help me

**Comment by Al3XKOoL** [comment]
Run this command from adb

adb logcat -b radio -v time -d > logcat_radio.log

And wait to get some network lost. 
After it hit crtl + c and share log here.

**Comment by Yuvrajroy10** [comment]
Wait...

**Comment by Yuvrajroy10** [comment]
Can I use terminal emulator

**Comment by Yuvrajroy10** [comment]
How can I use adb without pc. My pc is not working well

**Comment by Al3XKOoL** [comment]
You can get modem log with this app

https://play.google.com/store/apps/details?id=com.tortel.syslog

Syslog

**Comment by Yuvrajroy10** [comment]
Yes I have installed the app. Now what I need to do

**Comment by Yuvrajroy10** [comment]
Here is the modem log = https://mega.nz/#!E5lmTK6Z!CjCVWr5IzJqv-UUTNovrPt9W81PVNdYPCqtD5PnkJ2E

**Comment by Al3XKOoL** [comment]
Thanks, i look it as soon possible.

**Comment by Yuvrajroy10** [comment]
Ok. Thanks man

**Comment by Yuvrajroy10** [comment]
Hey. did you get the problem

**Comment by Al3XKOoL** [comment]
Your problem maybe is related with this:
https://github.com/Al3XKOoL/android_device_wiko_rainbow/issues/27

Test from clean install without touch volume buttons on calls.

**Comment by Yuvrajroy10** [comment]
Not this. I am getting another

**Comment by Klexer** [comment]
First of all, I remember the messages _Restricted access change_. But I have never seen them again after the second reboot, after SIM1 was initilized completely.

Anyway, I have counter-checked the syslog of the reported bug. 

**Requirement:** 2 or 3 reboots after installation to get sim card connection initialized
**Test activity:**  Download 2G (EDGE) and 3G (UMTS) during a phone call (WiFi deactivated)
**Test result` `:**` `No break up of connection.

I can confirm the first error message. But this doesn't cause a break up on my device.The error is probably related to 'Error loading rules'. I am afraid no one from Europe will face this bug because of a different CDMA standard. Maybe someone from India should counter-check. 

_My syslog:_

```
09-27 13:08:11.725 D/RilRequest( 1966): [4093]< RIL_REQUEST_CDMA_SET_BROADCAST_CONFIG error: com.android.internal.telephony.CommandException: REQUEST_NOT_SUPPORTED ret=
```

_Syslog of @Yuvrajroy10_:

```
08-24 20:16:23.238 D/RilRequest( 3973): [3739]< RIL_REQUEST_CDMA_SET_BROADCAST_CONFIG error: com.android.internal.telephony.CommandException: REQUEST_NOT_SUPPORTED ret=
08-24 20:16:23.256 D/use-Rlog/RLOG-RIL( 5116): here we go to error setBroadcastEx
08-24 20:16:23.257 D/RilRequest( 3973): [3740]< RIL_REQUEST_GSM_SET_BROADCAST_CONFIG error: com.android.internal.telephony.CommandException: GENERIC_FAILURE ret=
08-24 20:16:29.649 D/UiccCarrierPrivilegeRules( 3973): Error loading rules.
```

@Yuvrajroy10, can you tell more about your network settings? Is roaming allowed? Are there any restrictions, enhancements by your provider? How good is the connection (min. 3 bars)? Is the SIM card new (contacts)? Is the card reader clean and dry? How many times have you rebooted?

I have serious doubts that these errors have something to do with CyanogenMod.

**Comment by Al3XKOoL** [comment]
I think this network restricted message appear when lost coverage only, i have no problems on calls, sms or data.

**Comment by Yuvrajroy10** [comment]
No this is your Rom problem

**Comment by Al3XKOoL** [comment]
Do not provide any valid information, not does the relevant tests.
This bug does not seem to exist for any other user.
